// AUTO-GENERATED BY KADMOS.
// Compiler contract: kadmos.compiler.k02.v1
export type WorldState = "WAITING" | "ACTIVE" | "DELAYED_RETRY" | "COMPLETED" | "FAILED" | "REVOKED";
export type WorldDirective = "DISPATCH_PAYLOAD" | "PERSIST_RESULT" | "SCHEDULE_BACKOFF" | "ENQUEUE_FOR_PICKUP" | "TRIGGER_DEAD_LETTER_ALERT" | "NOTIFY_CANCELLATION" | "EVICT_STALE_WORKER";
export interface WorldContext {
  readonly "job_id": string;
  readonly "lock_token": string;
  readonly "lock_epoch": number;
  readonly "retries": number;
  readonly "max_retries": number;
  readonly "result_digest": string;
  readonly "failed_reason": string;
}
export interface StepRecord { readonly step: number; readonly state: WorldState; readonly action: string; readonly eventPayload?: Readonly<Record<string, unknown>>; readonly proposedDirective?: WorldDirective | null; }
export interface TransitionStepRequest { readonly transitionId: string; readonly eventPayload?: Readonly<Record<string, unknown>>; readonly proposedDirective?: WorldDirective | null; }
export interface StepVerdict { readonly allowed: boolean; readonly previousState: WorldState; readonly currentState: WorldState; readonly context: WorldContext; readonly directiveAllowed: WorldDirective | null; readonly violation?: { readonly code: string; readonly message: string; readonly violatedInvariant?: string; readonly shortestCounterexampleTrace: readonly StepRecord[]; }; }
export interface IWorldChecker { getState(): WorldState; getContext(): WorldContext; step(request: TransitionStepRequest): StepVerdict; reset(initialContext?: Partial<WorldContext> | null): void; rollbackLastStep(): void; }