// AUTO-GENERATED BY KADMOS.
// Compiler contract: kadmos.compiler.k02.v1
export type WorldState = "IDLE" | "RUNNING" | "BACKOFF_WAIT" | "COMPLETED" | "CIRCUIT_BROKEN";
export type WorldDirective = "DISPATCH_EXECUTION_DISPATCHER" | "RECORD_METRICS_AND_CLEANUP" | "SCHEDULE_TIMER_WAKEUP" | "TRIGGER_PAGER_ALERT";
export interface WorldContext {
  readonly "retry_count": number;
  readonly "max_retries": number;
  readonly "consecutive_failures": number;
  readonly "backoff_seconds": number;
}
export interface StepRecord { readonly step: number; readonly state: WorldState; readonly action: string; readonly eventPayload?: Readonly<Record<string, unknown>>; readonly proposedDirective?: WorldDirective | null; }
export interface TransitionStepRequest { readonly transitionId: string; readonly eventPayload?: Readonly<Record<string, unknown>>; readonly proposedDirective?: WorldDirective | null; }
export interface StepVerdict { readonly allowed: boolean; readonly previousState: WorldState; readonly currentState: WorldState; readonly context: WorldContext; readonly directiveAllowed: WorldDirective | null; readonly violation?: { readonly code: string; readonly message: string; readonly violatedInvariant?: string; readonly shortestCounterexampleTrace: readonly StepRecord[]; }; }
export interface IWorldChecker { getState(): WorldState; getContext(): WorldContext; step(request: TransitionStepRequest): StepVerdict; reset(initialContext?: Partial<WorldContext> | null): void; rollbackLastStep(): void; }