import type { WorldSpec } from "./types/world.js";

export interface PythonWorldProjection {
  readonly portsPy: string;
  readonly worldCheckerPy: string;
}

export function compileWorldSpecPython(spec: WorldSpec): PythonWorldProjection {
  const literal = (values: string[]) => values.length ? `Literal[${values.map(v => JSON.stringify(v)).join(", ")}]` : "None";
  const directives = [...new Set(spec.transitions.map(t => t.directive).filter((v): v is string => v !== null))];
  const fields = Object.keys(spec.context).map(name => `${JSON.stringify(name)}: int`).join(", ");
  const portsPy = `# AUTO-GENERATED BY KADMOS. DO NOT EDIT DIRECTLY.
from __future__ import annotations
from typing import TypedDict, Literal, Protocol, Optional, Any, Dict, List

WorldState = ${literal(spec.states.map(s => s.id))}
WorldDirective = ${literal(directives)}

WorldContext = TypedDict("WorldContext", {${fields}})

class StepRecord(TypedDict, total=False):
    step: int
    state: WorldState
    action: str
    eventPayload: Optional[Dict[str, Any]]
    proposedDirective: Optional[WorldDirective]

class TransitionStepRequest(TypedDict, total=False):
    transitionId: str
    eventPayload: Optional[Dict[str, Any]]
    proposedDirective: Optional[WorldDirective]

class ViolationRecord(TypedDict, total=False):
    code: str
    message: str
    violatedInvariant: Optional[str]
    shortestCounterexampleTrace: List[StepRecord]

class StepVerdict(TypedDict, total=False):
    allowed: bool
    previousState: WorldState
    currentState: WorldState
    context: WorldContext
    directiveAllowed: Optional[WorldDirective]
    violation: Optional[ViolationRecord]

class IWorldChecker(Protocol):
    def get_state(self) -> WorldState: ...
    def get_context(self) -> WorldContext: ...
    def step(self, request: TransitionStepRequest) -> StepVerdict: ...
    def reset(self, initial_context: Optional[Dict[str, int]] = None) -> None: ...
`;
  const embedded = JSON.stringify(JSON.stringify(spec));
  const worldCheckerPy = `# AUTO-GENERATED BY KADMOS. DO NOT EDIT DIRECTLY.
from __future__ import annotations
import json
import math
import re
from typing import Any
from ports import IWorldChecker

_WORLD = json.loads(${embedded})
_INITIAL = next(state["id"] for state in _WORLD["states"] if state.get("initial"))
_DEFAULTS = {name: definition.get("default", 0) for name, definition in _WORLD["context"].items()}
_PRECEDENCE = {"=>": 1, "||": 2, "&&": 3, "==": 4, "!=": 4, ">": 5, ">=": 5, "<": 5, "<=": 5, "+": 6, "-": 6, "*": 7, "/": 7}
_TOKEN = re.compile(r"\\s+|=>|==|!=|>=|<=|&&|\\|\\||[()+\\-*/<>!.]|\\d+(?:\\.\\d+)?|[A-Za-z_][A-Za-z_0-9]*|'(?:[^'\\\\]|\\\\.)*'")
_NAME = re.compile(r"[A-Za-z_][A-Za-z_0-9]*\\Z")
_EFFECT = re.compile(r"([A-Za-z_][A-Za-z_0-9]*)\\s*=\\s*(.+)\\Z", re.S)
_MAX_INTEGER = 9007199254740991
_UNDEFINED = object()


def _boolean(value: Any) -> bool:
    if type(value) is not bool:
        raise ValueError("INVALID_EXPRESSION: expected boolean operand")
    return value


def _number(value: Any) -> int | float:
    if type(value) not in (int, float) or not math.isfinite(value):
        raise ValueError("INVALID_EXPRESSION: expected number")
    return value


def _safe_integer(value: Any) -> bool:
    return type(value) in (int, float) and math.isfinite(value) and value == int(value) and abs(value) <= _MAX_INTEGER


def evaluate_world(expression: str | bool, environment: dict[str, Any]) -> Any:
    if type(expression) is bool:
        return expression
    if type(expression) is not str:
        raise ValueError("INVALID_EXPRESSION: expected expression")
    tokens = []
    offset = 0
    while offset < len(expression):
        match = _TOKEN.match(expression, offset)
        if match is None:
            raise ValueError("INVALID_EXPRESSION: invalid token")
        offset = match.end()
        if not match.group().isspace():
            tokens.append(match.group())
    position = 0

    def parse(minimum: int = 0) -> Any:
        nonlocal position
        if position >= len(tokens):
            raise ValueError("INVALID_EXPRESSION: missing operand")
        token = tokens[position]
        position += 1
        if token == "(":
            left = parse()
            if position >= len(tokens) or tokens[position] != ")":
                raise ValueError("INVALID_EXPRESSION: missing )")
            position += 1
        elif token in ("!", "-"):
            operand = parse(8)
            left = not _boolean(operand) if token == "!" else -_number(operand)
        elif token in ("true", "false"):
            left = token == "true"
        elif token == "null":
            left = None
        elif token.startswith("'"):
            left = token[1:-1].replace("\\\\'", "'")
        elif token[0].isdigit():
            left = float(token) if "." in token else int(token)
        elif _NAME.fullmatch(token):
            left = environment.get(token, _UNDEFINED)
            while position < len(tokens) and tokens[position] == ".":
                position += 1
                if position >= len(tokens) or not _NAME.fullmatch(tokens[position]):
                    raise ValueError("INVALID_EXPRESSION: property")
                property_name = tokens[position]
                position += 1
                left = left.get(property_name, _UNDEFINED) if type(left) is dict else _UNDEFINED
        else:
            raise ValueError("INVALID_EXPRESSION: invalid operand")
        while position < len(tokens):
            operator = tokens[position]
            rank = _PRECEDENCE.get(operator)
            if rank is None or rank < minimum:
                break
            position += 1
            right = parse(rank + (0 if operator == "=>" else 1))
            if operator in ("=>", "||", "&&"):
                l = _boolean(left)
                r = _boolean(right)
                if operator == "=>":
                    left = not l or r
                elif operator == "||":
                    left = l or r
                else:
                    left = l and r
            elif operator in ("==", "!="):
                if type(left) is dict and type(right) is dict:
                    equal = left is right
                else:
                    equal = (type(left) is type(right) or (type(left) in (int, float) and type(right) in (int, float))) and left == right
                left = equal if operator == "==" else not equal
            elif operator == ">":
                left = _number(left) > _number(right)
            elif operator == ">=":
                left = _number(left) >= _number(right)
            elif operator == "<":
                left = _number(left) < _number(right)
            elif operator == "<=":
                left = _number(left) <= _number(right)
            elif operator == "+":
                left = _number(left) + _number(right)
            elif operator == "-":
                left = _number(left) - _number(right)
            elif operator == "*":
                left = _number(left) * _number(right)
            else:
                left = _number(left) / _number(right)
        return left

    result = parse()
    if position != len(tokens):
        raise ValueError("INVALID_EXPRESSION: trailing token")
    return result


def sanitize_world_payload(raw: Any) -> dict[str, Any] | None:
    if raw is None:
        return None
    seen: set[int] = set()

    def copy(value: Any) -> Any:
        if isinstance(value, (list, tuple, set)):
            raise ValueError("INVALID_EVENT_PAYLOAD: must be an object")
        if value is None or type(value) in (str, bool, int):
            return value
        if type(value) is float and math.isfinite(value):
            return value
        if type(value) is not dict:
            raise ValueError("SECURITY_VIOLATION: invalid payload type")
        identity = id(value)
        if identity in seen:
            raise ValueError("SECURITY_VIOLATION: cyclic payload")
        seen.add(identity)
        try:
            result = {}
            for key, item in value.items():
                if type(key) is not str or key in ("__proto__", "constructor", "prototype"):
                    raise ValueError("SECURITY_VIOLATION: invalid payload key")
                result[key] = copy(item)
            return result
        finally:
            seen.remove(identity)

    if type(raw) is not dict:
        raise ValueError("INVALID_EVENT_PAYLOAD: must be an object")
    return copy(raw)


class WorldChecker(IWorldChecker):
    def __init__(self, initial_context: dict[str, int] | None = None):
        self._initial_context = dict(initial_context) if initial_context is not None else None
        self.state = _INITIAL
        self.context: dict[str, int] = {}
        self.history: list[dict[str, Any]] = []
        self._busy = False
        self.reset(initial_context)

    def get_state(self) -> str:
        return self.state

    def getState(self) -> str:
        return self.get_state()

    def get_context(self) -> dict[str, int]:
        return dict(self.context)

    def getContext(self) -> dict[str, int]:
        return self.get_context()

    def _bounds(self, values: dict[str, int]) -> str | None:
        for name, definition in _WORLD["context"].items():
            value = values.get(name)
            if not _safe_integer(value):
                return name
            if ("min" in definition and value < definition["min"]) or ("max" in definition and value > definition["max"]):
                return name
        return None

    def _invariant(self, state: str, values: dict[str, int], event: dict[str, Any] | None = None) -> str | None:
        environment = {**values, "state": state, "event": event or {}}
        for invariant in _WORLD["invariants"]:
            try:
                if evaluate_world(invariant["predicate"], environment) is not True:
                    return invariant["id"]
            except Exception as e:
                if isinstance(e, RuntimeError) and "REENTRANCY_DETECTED" in str(e):
                    raise
                return invariant["id"]
        return None

    def reset(self, initial_context: dict[str, int] | None = None) -> None:
        if self._busy:
            raise RuntimeError("REENTRANCY_DETECTED: reset called during active evaluation")
        self._busy = True
        try:
            candidate = dict(_DEFAULTS)
            if initial_context is None:
                initial_context = self._initial_context
            if initial_context is not None:
                if type(initial_context) is not dict:
                    raise ValueError("INVALID_BOUNDS: initial context")
                for name, value in initial_context.items():
                    if name not in _WORLD["context"] or not _safe_integer(value):
                        raise ValueError(f"INVALID_BOUNDS: {name}")
                    candidate[name] = int(value)
            invalid = self._bounds(candidate)
            if invalid:
                raise ValueError(f"INVALID_BOUNDS: {invalid}")
            violated = self._invariant(_INITIAL, candidate)
            if violated:
                raise ValueError(f"INITIAL_INVARIANT_FAILED: {violated}")
            self.state = _INITIAL
            self.context = candidate
            self.history = []
        finally:
            self._busy = False

    def step(self, request: dict[str, Any]) -> dict[str, Any]:
        if self._busy:
            raise RuntimeError("REENTRANCY_DETECTED: step called during active evaluation")
        self._busy = True
        previous = self.state
        original_context = dict(self.context)
        original_history = list(self.history)
        try:
            action = request.get("transitionId")
            try:
                payload = sanitize_world_payload(request.get("eventPayload"))
            except ValueError as error:
                trace = original_history + [{"step": len(original_history) + 1, "state": previous, "action": action}]
                return {"allowed": False, "previousState": previous, "currentState": previous, "context": original_context, "directiveAllowed": None, "violation": {"code": "SECURITY_VIOLATION", "message": str(error), "shortestCounterexampleTrace": trace}}
            record = {"step": len(original_history) + 1, "state": previous, "action": action}
            if payload is not None:
                record["eventPayload"] = payload
            if "proposedDirective" in request:
                record["proposedDirective"] = request["proposedDirective"]

            def reject(code: str, message: str, invariant: str | None = None) -> dict[str, Any]:
                violation = {"code": code, "message": message, "shortestCounterexampleTrace": original_history + [record]}
                if invariant is not None:
                    violation["violatedInvariant"] = invariant
                return {"allowed": False, "previousState": previous, "currentState": previous, "context": original_context, "directiveAllowed": None, "violation": violation}

            transition = next((item for item in _WORLD["transitions"] if item["id"] == action and item["from"] == previous), None)
            if transition is None:
                return reject("INVALID_TRANSITION", f"Transition '{action}' is not legal from state '{previous}'")
            if request.get("proposedDirective") != transition["directive"]:
                return reject("UNAUTHORIZED_DIRECTIVE", "Directive does not match declared transition")
            environment = lambda state, values: {**values, "state": state, "event": payload or {}}
            try:
                guard = evaluate_world(transition["guard"], environment(previous, original_context))
                if guard is not True:
                    return reject("GUARD_FAILED", "Guard condition failed")
            except Exception as e:
                if isinstance(e, RuntimeError) and "REENTRANCY_DETECTED" in str(e):
                    raise
                return reject("GUARD_FAILED", "Guard expression evaluation failed")
            candidate = dict(original_context)
            try:
                for effect in transition["effects"]:
                    match = _EFFECT.fullmatch(effect)
                    if match is None or match.group(1) not in _WORLD["context"]:
                        return reject("INVALID_EFFECT", "Invalid effect assignment target")
                    value = evaluate_world(match.group(2), environment(transition["to"], candidate))
                    if not _safe_integer(value):
                        return reject("INVALID_EFFECT", "Effect expression did not yield an integer")
                    candidate[match.group(1)] = int(value)
            except Exception as e:
                if isinstance(e, RuntimeError) and "REENTRANCY_DETECTED" in str(e):
                    raise
                return reject("INVALID_EFFECT", "Effect evaluation failed")
            invalid = self._bounds(candidate)
            if invalid:
                return reject("INVALID_BOUNDS", f"Context bound failed on '{invalid}'")
            violated = self._invariant(transition["to"], candidate, payload)
            if violated:
                return reject("INVARIANT_FAILED", f"Invariant violation: '{violated}'", violated)
            self.state = transition["to"]
            self.context = candidate
            self.history.append(record)
            return {"allowed": True, "previousState": previous, "currentState": self.state, "context": dict(candidate), "directiveAllowed": transition["directive"]}
        finally:
            self._busy = False
`;
  return { portsPy, worldCheckerPy };
}
